### ISSUE TITLE
No module named cms_toolbar

### ISSUE THREAD

**Issue by leesolway** [mishbahr/djangocms-usersettings2#1]
ImportError at /
No module named cms_toolbar

Latest version of the CMS changes the module name. to cms_toolbar(s)

**Comment by mishbahr** [comment]
Thanks for reporting. I'll push a fix asap.

**Comment by mishbahr** [comment]
Fixed. See https://github.com/mishbahr/djangocms-usersettings2/pull/2

**Comment by mishbahr** [comment]
@leesolway pushed updates to pypi. Thanks

Regards

Mishbah
